KF-3620
canonical/mlflow-prometheus-exporter pull request #4
Opened 2023-06-21 13:19 UTC by misohu

* Add exporter functionality
* Add Dockerfile
* Add Rockcraft.yaml
* Add integration tests

2023-06-21 15:44 UTC, beliaev-maksim requested changes

2023-06-21 20:42 UTC, ca-scribner commented on README.md
> +- `TIMEOUT`: The timeout for pooling new metrics (default: `30`).
"pooling" or "polling"?  And 30 what, seconds?

2023-06-21 20:43 UTC, ca-scribner commented on README.md
> +You can set these environment variables when running the Docker container or provide them in a configuration file.
This might be clearer with an example call.  Could just be a one liner `PORT=1234 MLFLOW_URL=stuff python mlflow_exporter.py`

2023-06-21 21:02 UTC, ca-scribner reviewed
a few minor comments but generally looks really good

2023-06-21 21:02 UTC, ca-scribner commented on .github/workflows/build_and_publish_call.yaml
Can we add some tests into the CI that publishes the image?  I don't think you need to actually use it in integration tests, but at least something that proves the image starts.  

Also, should the docker image build and publish even if the integration tests fail?

2023-06-21 21:10 UTC, i-chvets commented on mlflow_exporter/tests/integration/test_mlflow_exporter.py
> +    assert 'mlflow_metric{metric_name="num_runs"} 0' in response.text  # No runs so far
+1 for tenacity instead of sleep

2023-06-22 06:54 UTC, misohu commented on mlflow_exporter/mlflow_exporter.py
> +        setattr(namespace, self.dest, values)
its a function we use in other places I just moved it here :) basically either use env variable or argument or default

2023-06-22 08:24 UTC, misohu commented on .github/workflows/build_and_publish_call.yaml
There is actually test in the publish action but it got merget in the inital repo PR :) .... I addded condition to CI if integration fails I dont push

2023-06-22 08:27 UTC, misohu commented on .github/workflows/build_and_publish_call.yaml
Here is the line with test https://github.com/canonical/mlflow-prometheus-exporter/blob/main/.github/workflows/build_and_publish_call.yaml#L52

2023-06-22 08:34 UTC, beliaev-maksim commented on README.md
> +If you'd like to contribute to the MLflow Prometheus Exporter Docker image, feel free to fork this repository and submit a pull request. Contributions are always welcome!
```suggestion
If you'd like to contribute to the MLflow Prometheus Exporter, feel free to fork this repository and submit a pull request. Contributions are always welcome!
```

2023-06-23 12:55 UTC, i-chvets commented on rockcraft.yaml
> +version: "v1.0.0_22.04"
Let's have a version `v1.0.0_22.04_1`
I know we ARE "upstream" for this image, but we should be consistent. Plus. we might want to fix something without doing bump in v1.0.0.

2023-06-23 13:23 UTC, ca-scribner approved these changes
looks great! gj

2023-06-27 06:27 UTC, merged